name: Deploy to server

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        outputs:
            salida:

        steps:
            - name: Generar archivo
              run:
                echo "Archivo prueba, hola" >> test.log
            
            - name: Subir artefacto
              uses: actions/upload-artifact@v4
              with:
                name: archivo-test
                path: test.log
 
   


