name: Deploy to server

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        env:
            NAME: CodigoFacilito

        steps:
            - name: Hola mundo
              run: echo "Hola Mundo"  $NAME
      
    second_jobs:
        if: ${{ github.ref == 'refs/heads/main' }}
        needs: first_job
        runs-on: ubuntu-latest

        steps:
            - name: Hola mundo 2
              run: echo "Hola Mundo 2"


